import { Food } from '../db'

export const PRESET_FOODS: Omit<Food, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // Dairy
  {
    guid: 'food-milk',
    name: 'Milk',
    category: 'Dairy',
    allergenTags: ['dairy'],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-cheese',
    name: 'Cheese',
    category: 'Dairy',
    allergenTags: ['dairy'],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-yogurt',
    name: 'Yogurt',
    category: 'Dairy',
    allergenTags: ['dairy'],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-butter',
    name: 'Butter',
    category: 'Dairy',
    allergenTags: ['dairy'],
    isActive: false,
    isDefault: true,
  },

  // Proteins
  {
    guid: 'food-chicken',
    name: 'Chicken',
    category: 'Protein',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-beef',
    name: 'Beef',
    category: 'Protein',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-pork',
    name: 'Pork',
    category: 'Protein',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-salmon',
    name: 'Salmon',
    category: 'Protein',
    allergenTags: ['fish'],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-tuna',
    name: 'Tuna',
    category: 'Protein',
    allergenTags: ['fish'],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-shrimp',
    name: 'Shrimp',
    category: 'Protein',
    allergenTags: ['shellfish'],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-eggs',
    name: 'Eggs',
    category: 'Protein',
    allergenTags: ['eggs'],
    isActive: false,
    isDefault: true,
  },

  // Vegetables
  {
    guid: 'food-tomato',
    name: 'Tomato',
    category: 'Vegetable',
    allergenTags: ['nightshades'],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-potato',
    name: 'Potato',
    category: 'Vegetable',
    allergenTags: ['nightshades'],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-eggplant',
    name: 'Eggplant',
    category: 'Vegetable',
    allergenTags: ['nightshades'],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-bell-pepper',
    name: 'Bell Pepper',
    category: 'Vegetable',
    allergenTags: ['nightshades'],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-broccoli',
    name: 'Broccoli',
    category: 'Vegetable',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-spinach',
    name: 'Spinach',
    category: 'Vegetable',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-carrots',
    name: 'Carrots',
    category: 'Vegetable',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-lettuce',
    name: 'Lettuce',
    category: 'Vegetable',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },

  // Fruits
  {
    guid: 'food-apple',
    name: 'Apple',
    category: 'Fruit',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-banana',
    name: 'Banana',
    category: 'Fruit',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-orange',
    name: 'Orange',
    category: 'Fruit',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-strawberry',
    name: 'Strawberry',
    category: 'Fruit',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-blueberry',
    name: 'Blueberry',
    category: 'Fruit',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },

  // Grains
  {
    guid: 'food-bread',
    name: 'Bread',
    category: 'Grain',
    allergenTags: ['gluten'],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-rice',
    name: 'Rice',
    category: 'Grain',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-pasta',
    name: 'Pasta',
    category: 'Grain',
    allergenTags: ['gluten'],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-oats',
    name: 'Oats',
    category: 'Grain',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-quinoa',
    name: 'Quinoa',
    category: 'Grain',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },

  // Nuts & Seeds
  {
    guid: 'food-almonds',
    name: 'Almonds',
    category: 'Nuts & Seeds',
    allergenTags: ['nuts'],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-peanuts',
    name: 'Peanuts',
    category: 'Nuts & Seeds',
    allergenTags: ['nuts'],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-walnuts',
    name: 'Walnuts',
    category: 'Nuts & Seeds',
    allergenTags: ['nuts'],
    isActive: false,
    isDefault: true,
  },

  // Legumes
  {
    guid: 'food-soybeans',
    name: 'Soybeans',
    category: 'Legumes',
    allergenTags: ['soy'],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-tofu',
    name: 'Tofu',
    category: 'Legumes',
    allergenTags: ['soy'],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-black-beans',
    name: 'Black Beans',
    category: 'Legumes',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-chickpeas',
    name: 'Chickpeas',
    category: 'Legumes',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },

  // Beverages
  {
    guid: 'food-coffee',
    name: 'Coffee',
    category: 'Beverage',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-tea',
    name: 'Tea',
    category: 'Beverage',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-soda',
    name: 'Soda',
    category: 'Beverage',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'food-alcohol',
    name: 'Alcohol',
    category: 'Beverage',
    allergenTags: [],
    isActive: false,
    isDefault: true,
  },
]
