import { Symptom } from '../db'

export const PRESET_SYMPTOMS: Omit<Symptom, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // Physical Symptoms
  {
    guid: 'symptom-pain',
    name: 'Pain',
    category: 'Physical',
    description: 'General pain or discomfort',
    severityScale: {
      min: 1,
      max: 10,
      labels: { 1: 'Mild', 5: 'Moderate', 10: 'Severe' }
    },
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'symptom-swelling',
    name: 'Swelling',
    category: 'Physical',
    description: 'Inflammation or swelling',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'symptom-redness',
    name: 'Redness',
    category: 'Physical',
    description: 'Skin redness or inflammation',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'symptom-itching',
    name: 'Itching',
    category: 'Physical',
    description: 'Skin itching or irritation',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'symptom-burning',
    name: 'Burning Sensation',
    category: 'Physical',
    description: 'Burning or stinging sensation',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'symptom-fatigue',
    name: 'Fatigue',
    category: 'Physical',
    description: 'General tiredness or lack of energy',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'symptom-fever',
    name: 'Fever',
    category: 'Physical',
    description: 'Elevated body temperature',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'symptom-drainage',
    name: 'Drainage',
    category: 'Physical',
    description: 'Fluid drainage from lesion',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'symptom-tenderness',
    name: 'Tenderness',
    category: 'Physical',
    description: 'Sensitivity to touch',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'symptom-stiffness',
    name: 'Stiffness',
    category: 'Physical',
    description: 'Joint or muscle stiffness',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'symptom-headache',
    name: 'Headache',
    category: 'Physical',
    description: 'Head pain',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'symptom-nausea',
    name: 'Nausea',
    category: 'Physical',
    description: 'Feeling of sickness',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'symptom-dizziness',
    name: 'Dizziness',
    category: 'Physical',
    description: 'Feeling lightheaded or unsteady',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },

  // Cognitive Symptoms
  {
    guid: 'symptom-brain-fog',
    name: 'Brain Fog',
    category: 'Cognitive',
    description: 'Difficulty concentrating or thinking clearly',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'symptom-memory-issues',
    name: 'Memory Issues',
    category: 'Cognitive',
    description: 'Difficulty remembering things',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'symptom-confusion',
    name: 'Confusion',
    category: 'Cognitive',
    description: 'Mental confusion or disorientation',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },

  // Emotional Symptoms
  {
    guid: 'symptom-anxiety',
    name: 'Anxiety',
    category: 'Emotional',
    description: 'Feelings of worry or nervousness',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'symptom-depression',
    name: 'Depression',
    category: 'Emotional',
    description: 'Feelings of sadness or hopelessness',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'symptom-irritability',
    name: 'Irritability',
    category: 'Emotional',
    description: 'Easily annoyed or frustrated',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'symptom-mood-swings',
    name: 'Mood Swings',
    category: 'Emotional',
    description: 'Rapid changes in mood',
    severityScale: { min: 1, max: 10 },
    isActive: false,
    isDefault: true,
  },
]
