import { Trigger } from '../db'

export const PRESET_TRIGGERS: Omit<Trigger, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // Environmental Triggers
  {
    guid: 'trigger-heat',
    name: 'Heat',
    category: 'environmental',
    description: 'Hot weather or high temperatures',
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'trigger-humidity',
    name: 'Humidity',
    category: 'environmental',
    description: 'High humidity levels',
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'trigger-cold',
    name: 'Cold',
    category: 'environmental',
    description: 'Cold weather or low temperatures',
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'trigger-pollution',
    name: 'Air Pollution',
    category: 'environmental',
    description: 'Poor air quality',
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'trigger-allergens',
    name: 'Allergens',
    category: 'environmental',
    description: 'Pollen, dust, or other allergens',
    isActive: false,
    isDefault: true,
  },

  // Lifestyle Triggers
  {
    guid: 'trigger-stress',
    name: 'Stress',
    category: 'lifestyle',
    description: 'Mental or emotional stress',
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'trigger-lack-sleep',
    name: 'Lack of Sleep',
    category: 'lifestyle',
    description: 'Insufficient sleep or poor sleep quality',
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'trigger-exercise',
    name: 'Exercise',
    category: 'lifestyle',
    description: 'Physical activity or exercise',
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'trigger-tight-clothing',
    name: 'Tight Clothing',
    category: 'lifestyle',
    description: 'Wearing tight or restrictive clothing',
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'trigger-friction',
    name: 'Friction',
    category: 'lifestyle',
    description: 'Skin friction or rubbing',
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'trigger-smoking',
    name: 'Smoking',
    category: 'lifestyle',
    description: 'Tobacco use',
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'trigger-alcohol',
    name: 'Alcohol',
    category: 'lifestyle',
    description: 'Alcohol consumption',
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'trigger-dehydration',
    name: 'Dehydration',
    category: 'lifestyle',
    description: 'Insufficient water intake',
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'trigger-menstruation',
    name: 'Menstruation',
    category: 'lifestyle',
    description: 'Menstrual cycle',
    isActive: false,
    isDefault: true,
  },

  // Dietary Triggers
  {
    guid: 'trigger-dairy',
    name: 'Dairy Products',
    category: 'dietary',
    description: 'Consumption of dairy',
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'trigger-gluten',
    name: 'Gluten',
    category: 'dietary',
    description: 'Consumption of gluten',
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'trigger-sugar',
    name: 'Sugar',
    category: 'dietary',
    description: 'High sugar intake',
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'trigger-processed-food',
    name: 'Processed Foods',
    category: 'dietary',
    description: 'Highly processed food consumption',
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'trigger-nightshades',
    name: 'Nightshades',
    category: 'dietary',
    description: 'Tomatoes, peppers, eggplants, potatoes',
    isActive: false,
    isDefault: true,
  },
  {
    guid: 'trigger-caffeine',
    name: 'Caffeine',
    category: 'dietary',
    description: 'Coffee, tea, or energy drinks',
    isActive: false,
    isDefault: true,
  },
]
